services:
    behat.failure_screenshot_extension.listener.failure_screenshot:
        class: Zodyac\Behat\FailureScreenshotExtension\Listener\FailureScreenshotListener
        arguments: [%behat.failure_screenshot_extension.path%]
        tags:
            - { name: behat.event_subscriber }
